% Create a invertedFcoplanar antenna
% Generated by MATLAB(R) 9.8 and Antenna Toolbox 4.2.
% Generated on: 27-Oct-2022 12:11:16
% Link: https://www.ti.com/lit/an/swra117d/swra117d.pdf

%% Antenna Properties 
% Design antenna at frequency 2400000000Hz
F0 = 2.4e9;
antennaObject = design(invertedFcoplanar,F0);

%% Antenna Analysis 
% Define plot frequency 
plotFrequency = F0;
% Define frequency range 
%freqRange = (2160:24:2640) * 1e6;
freqRange = linspace(2.2e9,2.6e9,21);
% show for invertedFcoplanar
refImpedance = 50;
figure;
show(antennaObject) 
% impedance for invertedFcoplanar
figure;
impedance(antennaObject, freqRange) 
% s11 for invertedFcoplanar
figure;
s = sparameters(antennaObject, freqRange, refImpedance); 
rfplot(s) 
% pattern for invertedFcoplanar
figure;
pattern(antennaObject, plotFrequency) 
%%
antennaObject.RadiatorArmWidth = 0.0013879;
antennaObject.FeederArmWidth = 0.0013879;
%%
pcbAnt = pcbStack(antennaObject);
pcbAnt.BoardThickness = 1e-3;
d1 = dielectric('FR4');
d1.EpsilonR = 4.5;
d1.Thickness = 1e-3;
pcbAnt.Layers{2} = d1;
pcbAnt.BoardShape = antenna.Rectangle('Length', antennaObject.GroundPlaneLength, ...
'Width', antennaObject.GroundPlaneLength+2*antennaObject.Height, ...
'Center', [0 antennaObject.Height]);
show(pcbAnt)
